### ISSUE TITLE
Ability to sort Team members seems to have gone away

### ISSUE THREAD

**Issue by swpcap** [starverte/lifepointe#79]
I used to be able to assign a number to each team member to put them into the order that I want.  That is gone or not obvious.  Please add back in.

**Comment by mbeall** [comment]
Temporarily fixed, and will be fixed in Steel 1.3. See https://github.com/starverte/steel/issues/167

**Note**: This repository is inactive. sharethelife.org uses the custom theme [Trinity](https://github.com/starverte/trinity) — a child theme of [Flint](https://github.com/starverte/flint) — and the plugin [Steel](https://github.com/starverte/steel).
